INSERT INTO public.battles (id, first, first_power, second, second_power, winner, damage, battlefield, finishing) VALUES (1, 25, 10, 60, 10, 25, -6.3432, null, null);
INSERT INTO public.battles (id, first, first_power, second, second_power, winner, damage, battlefield, finishing) VALUES (2, 43, 10, 62, 10, 43, -1.9807, null, null);
INSERT INTO public.battles (id, first, first_power, second, second_power, winner, damage, battlefield, finishing) VALUES (3, 21, 10, 49, 10, 49, 7.3762, null, null);
INSERT INTO public.battles (id, first, first_power, second, second_power, winner, damage, battlefield, finishing) VALUES (4, 5, 10, 51, 10, 51, 7.9827, null, null);
INSERT INTO public.battles (id, first, first_power, second, second_power, winner, damage, battlefield, finishing) VALUES (5, 32, 10, 44, 10, 44, 4.1985, null, null);
INSERT INTO public.battles (id, first, first_power, second, second_power, winner, damage, battlefield, finishing) VALUES (6, 7, 10, 22, 10, 22, 7.294, null, null);
INSERT INTO public.battles (id, first, first_power, second, second_power, winner, damage, battlefield, finishing) VALUES (7, 16, 10, 64, 10, 64, 0.9002, null, null);
INSERT INTO public.battles (id, first, first_power, second, second_power, winner, damage, battlefield, finishing) VALUES (8, 55, 10, 44, 14.1985, 55, -3.3502, null, null);
INSERT INTO public.battles (id, first, first_power, second, second_power, winner, damage, battlefield, finishing) VALUES (9, 3, 10, 38, 10, 38, 0.3144, null, null);
INSERT INTO public.battles (id, first, first_power, second, second_power, winner, damage, battlefield, finishing) VALUES (10, 20, 10, 71, 10, 71, 8.4653, null, null);
INSERT INTO public.battles (id, first, first_power, second, second_power, winner, damage, battlefield, finishing) VALUES (11, 27, 10, 34, 10, 34, 0.4241, null, null);
INSERT INTO public.battles (id, first, first_power, second, second_power, winner, damage, battlefield, finishing) VALUES (12, 30, 10, 65, 10, 65, 2.8284, null, null);
INSERT INTO public.battles (id, first, first_power, second, second_power, winner, damage, battlefield, finishing) VALUES (13, 57, 10, 70, 10, 70, 8.0324, null, null);
INSERT INTO public.battles (id, first, first_power, second, second_power, winner, damage, battlefield, finishing) VALUES (14, 48, 10, 53, 10, 48, -6.1068, null, null);
INSERT INTO public.battles (id, first, first_power, second, second_power, winner, damage, battlefield, finishing) VALUES (15, 45, 10, 58, 10, 45, -9.9894, null, null);
INSERT INTO public.battles (id, first, first_power, second, second_power, winner, damage, battlefield, finishing) VALUES (16, 63, 10, 71, 18.4653, 71, 16.0795, null, null);
INSERT INTO public.battles (id, first, first_power, second, second_power, winner, damage, battlefield, finishing) VALUES (17, 36, 10, 70, 18.0324, 70, 14.2866, null, null);
INSERT INTO public.battles (id, first, first_power, second, second_power, winner, damage, battlefield, finishing) VALUES (18, 12, 10, 66, 10, 66, 8.0398, null, null);
INSERT INTO public.battles (id, first, first_power, second, second_power, winner, damage, battlefield, finishing) VALUES (19, 54, 10, 68, 10, 68, 8.9136, null, null);
INSERT INTO public.battles (id, first, first_power, second, second_power, winner, damage, battlefield, finishing) VALUES (20, 14, 10, 43, 11.9807, 14, -8.2209, null, null);
INSERT INTO public.battles (id, first, first_power, second, second_power, winner, damage, battlefield, finishing) VALUES (21, 56, 10, 51, 17.9827, 51, 6.2071, null, null);
INSERT INTO public.battles (id, first, first_power, second, second_power, winner, damage, battlefield, finishing) VALUES (22, 72, 10, 45, 19.9894, 45, 1.517, null, null);
INSERT INTO public.battles (id, first, first_power, second, second_power, winner, damage, battlefield, finishing) VALUES (23, 1, 10, 35, 10, 35, 8.13, null, null);
INSERT INTO public.battles (id, first, first_power, second, second_power, winner, damage, battlefield, finishing) VALUES (24, 2, 10, 70, 32.319, 70, 2.9531, null, null);
INSERT INTO public.battles (id, first, first_power, second, second_power, winner, damage, battlefield, finishing) VALUES (25, 19, 10, 48, 16.1068, 19, -0.3141, null, null);
INSERT INTO public.battles (id, first, first_power, second, second_power, winner, damage, battlefield, finishing) VALUES (26, 55, 13.3502, 70, 35.2721, 70, 28.1099, null, null);
INSERT INTO public.battles (id, first, first_power, second, second_power, winner, damage, battlefield, finishing) VALUES (27, 13, 10, 17, 10, 13, -9.6987, null, null);
INSERT INTO public.battles (id, first, first_power, second, second_power, winner, damage, battlefield, finishing) VALUES (28, 6, 10, 38, 10.3144, 38, 4.077, null, null);
INSERT INTO public.battles (id, first, first_power, second, second_power, winner, damage, battlefield, finishing) VALUES (29, 46, 10, 70, 63.382, 70, 17.9406, null, null);
INSERT INTO public.battles (id, first, first_power, second, second_power, winner, damage, battlefield, finishing) VALUES (30, 33, 10, 37, 10, 33, -1.5617, null, null);
INSERT INTO public.battles (id, first, first_power, second, second_power, winner, damage, battlefield, finishing) VALUES (31, 29, 10, 70, 81.3226, 70, 56.5245, null, null);
INSERT INTO public.battles (id, first, first_power, second, second_power, winner, damage, battlefield, finishing) VALUES (32, 23, 10, 49, 17.3762, 49, 3.3017, null, null);
INSERT INTO public.battles (id, first, first_power, second, second_power, winner, damage, battlefield, finishing) VALUES (33, 50, 10, 59, 10, 59, 6.7558, null, null);
INSERT INTO public.battles (id, first, first_power, second, second_power, winner, damage, battlefield, finishing) VALUES (34, 26, 10, 31, 10, 26, -0.9173, null, null);
INSERT INTO public.battles (id, first, first_power, second, second_power, winner, damage, battlefield, finishing) VALUES (35, 34, 10.4241, 59, 16.7558, 59, 11.8677, null, null);
INSERT INTO public.battles (id, first, first_power, second, second_power, winner, damage, battlefield, finishing) VALUES (36, 25, 16.3432, 66, 18.0398, 25, -9.098, null, null);
INSERT INTO public.battles (id, first, first_power, second, second_power, winner, damage, battlefield, finishing) VALUES (37, 52, 10, 22, 17.294, 22, 11.3641, null, null);
INSERT INTO public.battles (id, first, first_power, second, second_power, winner, damage, battlefield, finishing) VALUES (38, 9, 10, 59, 28.6235, 59, 19.3733, null, null);
INSERT INTO public.battles (id, first, first_power, second, second_power, winner, damage, battlefield, finishing) VALUES (39, 68, 18.9136, 14, 18.2209, 68, -12.9691, null, null);
INSERT INTO public.battles (id, first, first_power, second, second_power, winner, damage, battlefield, finishing) VALUES (40, 69, 10, 35, 18.13, 35, 11.2347, null, null);
INSERT INTO public.battles (id, first, first_power, second, second_power, winner, damage, battlefield, finishing) VALUES (41, 11, 10, 47, 10, 11, -3.7081, null, null);
INSERT INTO public.battles (id, first, first_power, second, second_power, winner, damage, battlefield, finishing) VALUES (42, 39, 10, 67, 10, 39, -4.0065, null, null);
INSERT INTO public.battles (id, first, first_power, second, second_power, winner, damage, battlefield, finishing) VALUES (43, 71, 34.5448, 38, 14.3914, 71, -34.4638, null, null);
INSERT INTO public.battles (id, first, first_power, second, second_power, winner, damage, battlefield, finishing) VALUES (44, 42, 10, 22, 28.6581, 22, 27.6985, null, null);
INSERT INTO public.battles (id, first, first_power, second, second_power, winner, damage, battlefield, finishing) VALUES (45, 8, 10, 64, 10.9002, 8, -6.9996, null, null);
INSERT INTO public.battles (id, first, first_power, second, second_power, winner, damage, battlefield, finishing) VALUES (46, 24, 10, 13, 19.6987, 13, 2.4501, null, null);
INSERT INTO public.battles (id, first, first_power, second, second_power, winner, damage, battlefield, finishing) VALUES (47, 40, 10, 71, 69.0086, 71, 3.6914, null, null);
INSERT INTO public.battles (id, first, first_power, second, second_power, winner, damage, battlefield, finishing) VALUES (48, 45, 21.5064, 71, 72.7, 71, 41.9356, null, null);
INSERT INTO public.battles (id, first, first_power, second, second_power, winner, damage, battlefield, finishing) VALUES (49, 10, 10, 71, 114.6356, 71, 23.0646, null, null);
INSERT INTO public.battles (id, first, first_power, second, second_power, winner, damage, battlefield, finishing) VALUES (50, 33, 11.5617, 70, 137.8471, 70, 23.9372, null, null);
INSERT INTO public.battles (id, first, first_power, second, second_power, winner, damage, battlefield, finishing) VALUES (51, 65, 12.8284, 8, 16.9996, 8, 7.694, null, null);
INSERT INTO public.battles (id, first, first_power, second, second_power, winner, damage, battlefield, finishing) VALUES (52, 41, 10, 35, 29.3647, 41, -2.0629, null, null);
INSERT INTO public.battles (id, first, first_power, second, second_power, winner, damage, battlefield, finishing) VALUES (53, 73, 10, 13, 22.1488, 13, 21.216, null, null);
INSERT INTO public.battles (id, first, first_power, second, second_power, winner, damage, battlefield, finishing) VALUES (54, 61, 10, 22, 56.3566, 22, 19.4006, null, null);
INSERT INTO public.battles (id, first, first_power, second, second_power, winner, damage, battlefield, finishing) VALUES (55, 26, 10.9173, 22, 75.7572, 22, 49.28, null, null);
INSERT INTO public.battles (id, first, first_power, second, second_power, winner, damage, battlefield, finishing) VALUES (56, 51, 24.1898, 59, 47.9968, 59, 7.0364, null, null);
INSERT INTO public.battles (id, first, first_power, second, second_power, winner, damage, battlefield, finishing) VALUES (57, 4, 10, 19, 10.3141, 4, -1.3699, null, null);
INSERT INTO public.battles (id, first, first_power, second, second_power, winner, damage, battlefield, finishing) VALUES (58, 70, 161.7843, 22, 125.0372, 70, -46.613, null, null);
INSERT INTO public.battles (id, first, first_power, second, second_power, winner, damage, battlefield, finishing) VALUES (59, 28, 10, 25, 25.4412, 25, 13.2884, null, null);
INSERT INTO public.battles (id, first, first_power, second, second_power, winner, damage, battlefield, finishing) VALUES (60, 68, 31.8827, 71, 137.7002, 71, 30.5044, null, null);
INSERT INTO public.battles (id, first, first_power, second, second_power, winner, damage, battlefield, finishing) VALUES (61, 15, 10, 39, 14.0065, 15, -4.036, null, null);
INSERT INTO public.battles (id, first, first_power, second, second_power, winner, damage, battlefield, finishing) VALUES (62, 18, 10, 4, 11.3699, 18, -7.1379, null, null);
INSERT INTO public.battles (id, first, first_power, second, second_power, winner, damage, battlefield, finishing) VALUES (63, 71, 168.2046, 49, 20.6779, 71, -33.1428, null, null);
INSERT INTO public.battles (id, first, first_power, second, second_power, winner, damage, battlefield, finishing) VALUES (64, 71, 201.3474, 13, 43.3648, 71, -29.2286, null, null);
INSERT INTO public.battles (id, first, first_power, second, second_power, winner, damage, battlefield, finishing) VALUES (65, 59, 55.0332, 18, 17.1379, 59, -18.9092, null, null);
INSERT INTO public.battles (id, first, first_power, second, second_power, winner, damage, battlefield, finishing) VALUES (66, 11, 13.7081, 15, 14.036, 11, -9.7659, null, null);
INSERT INTO public.battles (id, first, first_power, second, second_power, winner, damage, battlefield, finishing) VALUES (67, 41, 12.0629, 59, 73.9424, 59, 57.0779, null, null);
INSERT INTO public.battles (id, first, first_power, second, second_power, winner, damage, battlefield, finishing) VALUES (68, 11, 23.474, 25, 38.7296, 25, 10.3969, null, null);
INSERT INTO public.battles (id, first, first_power, second, second_power, winner, damage, battlefield, finishing) VALUES (69, 71, 230.576, 59, 131.0203, 71, -152.8077, null, null);
INSERT INTO public.battles (id, first, first_power, second, second_power, winner, damage, battlefield, finishing) VALUES (70, 25, 49.1265, 71, 383.3837, 71, 223.0291, null, null);
INSERT INTO public.battles (id, first, first_power, second, second_power, winner, damage, battlefield, finishing) VALUES (71, 70, 208.3973, 71, 606.4128, 71, 403.6209, null, null);
INSERT INTO public.battles (id, first, first_power, second, second_power, winner, damage, battlefield, finishing) VALUES (72, 8, 24.6936, 71, 1010.0337, 71, 454.4806, null, null);

INSERT INTO public.characters (id, name, sex, alignment, universe, power, image) VALUES (8, 'Шива', 'f', 'evil', 'mortal kombat', -454.4806, 'shiva.jpg');
INSERT INTO public.characters (id, name, sex, alignment, universe, power, image) VALUES (70, 'Арктур Менгск', 'm', 'evil', 'star craft', -403.6209, 'menks.jpg');
INSERT INTO public.characters (id, name, sex, alignment, universe, power, image) VALUES (25, 'Рамси Сноу', 'm', 'evil', 'game of thrones', -223.0291, 'ramsi.png');
INSERT INTO public.characters (id, name, sex, alignment, universe, power, image) VALUES (59, 'Кэтрин Джейнвэй', 'f', 'good', 'star track', -152.8077, 'janeway.jpg');
INSERT INTO public.characters (id, name, sex, alignment, universe, power, image) VALUES (41, 'Кайло Рен', 'm', 'evil', 'star wars', -57.0779, 'kayloren.jpeg');
INSERT INTO public.characters (id, name, sex, alignment, universe, power, image) VALUES (29, 'Мелисандра', 'f', 'evil', 'game of thrones', -56.5245, 'milsiandra.jpeg');
INSERT INTO public.characters (id, name, sex, alignment, universe, power, image) VALUES (26, 'Дрого', 'm', 'neutral', 'game of thrones', -49.28, 'drogo.png');
INSERT INTO public.characters (id, name, sex, alignment, universe, power, image) VALUES (22, 'Санса Старк', 'f', 'good', 'game of thrones', -46.613, 'sansa.jpg');
INSERT INTO public.characters (id, name, sex, alignment, universe, power, image) VALUES (45, 'Армитаж Хакс', 'm', 'evil', 'star wars', -41.9356, 'haks.png');
INSERT INTO public.characters (id, name, sex, alignment, universe, power, image) VALUES (38, 'Дарт Мол', 'm', 'evil', 'star wars', -34.4638, 'darthmoll.jpeg');
INSERT INTO public.characters (id, name, sex, alignment, universe, power, image) VALUES (49, 'Гривус', 'm', 'evil', 'star wars', -33.1428, 'grivus.jpeg');
INSERT INTO public.characters (id, name, sex, alignment, universe, power, image) VALUES (68, 'Джим Рейнор', 'm', 'good', 'star craft', -30.5044, 'rainor.jpg');
INSERT INTO public.characters (id, name, sex, alignment, universe, power, image) VALUES (13, 'Драко Малфой', 'm', 'evil', 'harry potter', -29.2286, 'drako.jpg');
INSERT INTO public.characters (id, name, sex, alignment, universe, power, image) VALUES (55, 'Таша Яр', 'f', 'good', 'star track', -28.1099, 'yar.jpg');
INSERT INTO public.characters (id, name, sex, alignment, universe, power, image) VALUES (42, 'Рей', 'f', 'good', 'star wars', -27.6985, 'ray.jpeg');
INSERT INTO public.characters (id, name, sex, alignment, universe, power, image) VALUES (33, 'Йенифер', 'f', 'good', 'the witcher', -23.9372, 'jenipher.jpg');
INSERT INTO public.characters (id, name, sex, alignment, universe, power, image) VALUES (10, 'Гарри Поттер', 'm', 'good', 'harry potter', -23.0646, 'poter.jpeg');
INSERT INTO public.characters (id, name, sex, alignment, universe, power, image) VALUES (73, 'Алесса Гиллеспи', 'f', 'evil', 'silent hill', -21.216, 'alexa.jpg');
INSERT INTO public.characters (id, name, sex, alignment, universe, power, image) VALUES (61, 'Б-Эланна Торрес', 'f', 'good', 'star track', -19.4006, 'belanna.jpg');
INSERT INTO public.characters (id, name, sex, alignment, universe, power, image) VALUES (9, 'Горо', 'm', 'evil', 'mortal kombat', -19.3733, 'gorro.jpg');
INSERT INTO public.characters (id, name, sex, alignment, universe, power, image) VALUES (18, 'Китнисс Эвердин', 'f', 'good', 'the hunger games', -18.9092, 'kitnes.jpg');
INSERT INTO public.characters (id, name, sex, alignment, universe, power, image) VALUES (46, 'Ахсока Тано', 'f', 'good', 'star wars', -17.9406, 'ahsoka.jpg');
INSERT INTO public.characters (id, name, sex, alignment, universe, power, image) VALUES (63, 'Клэр', 'f', 'good', 'claymore', -16.0795, 'clare.jpg');
INSERT INTO public.characters (id, name, sex, alignment, universe, power, image) VALUES (36, 'Квай Гон Джин', 'm', 'good', 'star wars', -14.2866, 'qvaygon.jpeg');
INSERT INTO public.characters (id, name, sex, alignment, universe, power, image) VALUES (28, 'Тирион Ланнистер', 'm', 'good', 'game of thrones', -13.2884, 'tirion.jpeg');
INSERT INTO public.characters (id, name, sex, alignment, universe, power, image) VALUES (14, 'Гермиона Грейджер', 'f', 'good', 'harry potter', -12.9691, 'germiona.jpg');
INSERT INTO public.characters (id, name, sex, alignment, universe, power, image) VALUES (34, 'Йода', 'm', 'good', 'star wars', -11.8677, 'yoda.jpeg');
INSERT INTO public.characters (id, name, sex, alignment, universe, power, image) VALUES (52, 'Диана Трой', 'f', 'good', 'star track', -11.3641, 'diana.jpg');
INSERT INTO public.characters (id, name, sex, alignment, universe, power, image) VALUES (69, 'Мэтт Хорнер', 'm', 'good', 'star craft', -11.2347, 'met.jpg');
INSERT INTO public.characters (id, name, sex, alignment, universe, power, image) VALUES (11, 'Рон Узли', 'm', 'good', 'harry potter', -10.3969, 'ron.jpg');
INSERT INTO public.characters (id, name, sex, alignment, universe, power, image) VALUES (58, '7 из 9', 'f', 'good', 'star track', -9.9894, '7of9.jpg');
INSERT INTO public.characters (id, name, sex, alignment, universe, power, image) VALUES (15, 'Миневра Макгонокал', 'f', 'good', 'harry potter', -9.7659, 'mcgonagall.jpg');
INSERT INTO public.characters (id, name, sex, alignment, universe, power, image) VALUES (17, 'Доби', 'm', 'neutral', 'harry potter', -9.6987, 'doby.jpg');
INSERT INTO public.characters (id, name, sex, alignment, universe, power, image) VALUES (66, 'Агент Смит', 'm', 'evil', 'the matrix', -9.098, 'smith.jpeg');
INSERT INTO public.characters (id, name, sex, alignment, universe, power, image) VALUES (54, 'Уильям Райкерр', 'm', 'good', 'star track', -8.9136, 'rayker.jpg');
INSERT INTO public.characters (id, name, sex, alignment, universe, power, image) VALUES (20, 'Дейенерис Таргариен', 'f', 'good', 'game of thrones', -8.4653, 'deaneris.jpeg');
INSERT INTO public.characters (id, name, sex, alignment, universe, power, image) VALUES (43, 'Сноук', 'm', 'evil', 'star wars', -8.2209, 'snouk.jpeg');
INSERT INTO public.characters (id, name, sex, alignment, universe, power, image) VALUES (1, 'Соня Блейд', 'f', 'good', 'mortal kombat', -8.13, 'sonya.png');
INSERT INTO public.characters (id, name, sex, alignment, universe, power, image) VALUES (12, 'Волон Де Морт', 'm', 'evil', 'harry potter', -8.0398, 'volendemort.jpg');
INSERT INTO public.characters (id, name, sex, alignment, universe, power, image) VALUES (57, 'Дженис Рэнд', 'f', 'good', 'star track', -8.0324, 'rend.jpeg');
INSERT INTO public.characters (id, name, sex, alignment, universe, power, image) VALUES (5, 'Куан Чи', 'm', 'evil', 'mortal kombat', -7.9827, 'kvanchi.jpg');
INSERT INTO public.characters (id, name, sex, alignment, universe, power, image) VALUES (65, 'Тринити', 'f', 'good', 'the matrix', -7.694, 'triniti.jpg');
INSERT INTO public.characters (id, name, sex, alignment, universe, power, image) VALUES (21, 'Арья Старк', 'f', 'good', 'game of thrones', -7.3762, 'aria.png');
INSERT INTO public.characters (id, name, sex, alignment, universe, power, image) VALUES (7, 'Синдел', 'f', 'evil', 'mortal kombat', -7.294, 'sindel.png');
INSERT INTO public.characters (id, name, sex, alignment, universe, power, image) VALUES (4, 'Шанг Цунг', 'm', 'evil', 'mortal kombat', -7.1379, 'shanzung.jpg');
INSERT INTO public.characters (id, name, sex, alignment, universe, power, image) VALUES (51, 'Беверли Крашер', 'f', 'good', 'star track', -7.0364, 'bevarli.jpg');
INSERT INTO public.characters (id, name, sex, alignment, universe, power, image) VALUES (64, 'Мотоко Кусонаги', 'f', 'good', 'ghost in the shell', -6.9996, 'motoco.jpg');
INSERT INTO public.characters (id, name, sex, alignment, universe, power, image) VALUES (50, 'Жан Люк Пикард', 'm', 'good', 'star track', -6.7558, 'picard.jpg');
INSERT INTO public.characters (id, name, sex, alignment, universe, power, image) VALUES (60, 'Чакотай', 'm', 'good', 'star track', -6.3432, 'chakotay.jpg');
INSERT INTO public.characters (id, name, sex, alignment, universe, power, image) VALUES (56, 'Спок', 'm', 'good', 'star track', -6.2071, 'spok.jpg');
INSERT INTO public.characters (id, name, sex, alignment, universe, power, image) VALUES (53, 'Дейта', 'm', 'good', 'star track', -6.1068, 'deyta.jpg');
INSERT INTO public.characters (id, name, sex, alignment, universe, power, image) VALUES (32, 'Трис Меригольт', 'f', 'good', 'the witcher', -4.1985, 'tris.jpeg');
INSERT INTO public.characters (id, name, sex, alignment, universe, power, image) VALUES (6, 'Лю Канг', 'm', 'good', 'mortal kombat', -4.077, 'lukang.jpg');
INSERT INTO public.characters (id, name, sex, alignment, universe, power, image) VALUES (39, 'Дарт Вейдер', 'm', 'evil', 'star wars', -4.036, 'dartvaidor.jpeg');
INSERT INTO public.characters (id, name, sex, alignment, universe, power, image) VALUES (67, 'Сара Керриган', 'f', 'neutral', 'star craft', -4.0065, 'kerrigan.jpg');
INSERT INTO public.characters (id, name, sex, alignment, universe, power, image) VALUES (47, 'Асажж Вентресс', 'f', 'evil', 'star wars', -3.7081, 'asash.jpg');
INSERT INTO public.characters (id, name, sex, alignment, universe, power, image) VALUES (40, 'Люк Скайуокер', 'm', 'good', 'star wars', -3.6914, 'luk.jpeg');
INSERT INTO public.characters (id, name, sex, alignment, universe, power, image) VALUES (44, 'Лея Органо', 'm', 'good', 'star wars', -3.3502, 'leya.jpg');
INSERT INTO public.characters (id, name, sex, alignment, universe, power, image) VALUES (23, 'Визерис Таргариен', 'm', 'evil', 'game of thrones', -3.3017, 'viserys.jpg');
INSERT INTO public.characters (id, name, sex, alignment, universe, power, image) VALUES (2, 'Рейден', 'm', 'good', 'mortal kombat', -2.9531, 'raiden.jpg');
INSERT INTO public.characters (id, name, sex, alignment, universe, power, image) VALUES (30, 'Герольд', 'm', 'good', 'the witcher', -2.8284, 'whitcher.png');
INSERT INTO public.characters (id, name, sex, alignment, universe, power, image) VALUES (24, 'Серсея Ланнистер', 'f', 'evil', 'game of thrones', -2.4501, 'serseia.jpg');
INSERT INTO public.characters (id, name, sex, alignment, universe, power, image) VALUES (35, 'Оби Ван Кеноби', 'm', 'good', 'star wars', -2.0629, 'obivan.jpeg');
INSERT INTO public.characters (id, name, sex, alignment, universe, power, image) VALUES (62, 'Кесс', 'm', 'good', 'star track', -1.9807, 'kes.jpg');
INSERT INTO public.characters (id, name, sex, alignment, universe, power, image) VALUES (37, 'Палпатин', 'm', 'evil', 'star wars', -1.5617, 'palpatin.jpg');
INSERT INTO public.characters (id, name, sex, alignment, universe, power, image) VALUES (72, 'Абатур', 'm', 'neutral', 'star craft', -1.517, 'abadur.jpg');
INSERT INTO public.characters (id, name, sex, alignment, universe, power, image) VALUES (19, 'Джон Сноу', 'm', 'good', 'game of thrones', -1.3699, 'snou.jpg');
INSERT INTO public.characters (id, name, sex, alignment, universe, power, image) VALUES (31, 'Цири', 'f', 'good', 'the witcher', -0.9173, 'ciry.jpg');
INSERT INTO public.characters (id, name, sex, alignment, universe, power, image) VALUES (16, 'Беллатриса Лестрейндж', 'f', 'evil', 'harry potter', -0.9002, 'belotrisa.jpg');
INSERT INTO public.characters (id, name, sex, alignment, universe, power, image) VALUES (27, 'Джоффри Баратеон', 'm', 'good', 'game of thrones', -0.4241, 'jofri.jpeg');
INSERT INTO public.characters (id, name, sex, alignment, universe, power, image) VALUES (3, 'Шао Кан', 'm', 'evil', 'mortal kombat', -0.3144, 'shaokan.jpg');
INSERT INTO public.characters (id, name, sex, alignment, universe, power, image) VALUES (48, 'Эйла Секура', 'f', 'good', 'star wars', -0.3141, 'secura.jpg');
INSERT INTO public.characters (id, name, sex, alignment, universe, power, image) VALUES (71, 'Нова', 'f', 'good', 'star craft', 1464.5143, 'nova.jpg');